apiVersion: v1
kind: Namespace
metadata:
  name: aplicacioncurso
  
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicaciondeploymentcurso
  namespace: aplicacioncurso
spec:
  selector:
    matchLabels:
      app: aplicaciondeploymentcurso 
    replicas: 1
  template:
    metadata:
      labels:
        app: aplicaciondeploymentcurso
        role: aplicaciondeploymentcurso
    spec:
      containers:
        - name: aplicaciondeploymentcurso
          image: carlarodriguezag/app:devops
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: aplicaciondeploymentcurso

---
apiVersion: v1
kind: Service
metadata:
  name: aplicacionservicecurso
  namespace: aplicacioncurso
  labels:
    app: aplicaciondeploymentcurso
spec:
  selector:
   app: aplicaciondeploymentcurso
  type: ClusterIP
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 80
  selector:
    role: aplicaciondeploymentcurso
