apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacion
  namespace: aplicacion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aplicacion 
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
  template:
    metadata:
      labels:
        app: aplicacion
        role: aplicacion
    spec:
      containers:
        - name: aplicacion
          image: carlarodriguezag/app:devops
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: aplicacion

---
apiVersion: v1
kind: Service
metadata:
  name: aplicacion
   namespace: aplicacion
  labels:
    app: aplicacion
spec:
  selector:
   app: aplicacion
  type: ClusterIP
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 80
  selector:
    role: aplicacion
    