apiVersion: v1
kind: Namespace
metadata:
  name: aplicacioncurso
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: aplicacioncurso
type: Opaque
data:
  ROOT_PASSWORD: bWktY29udHJhc2XDsWEtZGVsLWN1cnNv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: aplicacioncurso
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: carlarodriguezag/phpmyadmin:devops
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysqlcursoservice
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: aplicacioncurso
spec:
  type: ClusterIP
  selector:
    app: admin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80