apiVersion: v1
kind: Namespace
metadata:
  name: aplicacioncurso
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmindeploymentcurso
  namespace: aplicacioncurso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmindeploymentcurso
          image: carlarodriguezag/phpmyadmin:devops
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysqlservicecurso
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: ROOT_PASSWORD
          volumeMounts: 
            - name: sessions
              mountPath: /sessions
      volumes:
        - name: sessions
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadminservicecurso
  namespace: aplicacioncurso
spec:
  type: ClusterIP
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80