apiVersion: v1
kind: Namespace
metadata:
  name: aplicacioncurso
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlvolumencurso
  namespace: aplicacioncurso
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: aplicacioncurso
type: Opaque
data:
  ROOT_PASSWORD: bWktY29udHJhc2XDsWEtZGVsLWN1cnNv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldeploymentcurso
  namespace: aplicacioncurso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysqldeploymentcurso
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: ROOT_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysqlvolumencurso 
              mountPath: "/var/lib/mysql"  
      volumes:
        - name: mysqlvolumencurso
          persistentVolumeClaim:
            claimName: mysqlvolumencurso

---
apiVersion: v1
kind: Service
metadata:
  name: mysqlservicecurso
  namespace: aplicacioncurso
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306