apiVersion: v1
kind: Namespace
metadata:
  name: aplicacioncurso

---
apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecretcurso
  namespace: aplicacioncurso
type: Opaque
data:
  ROOT_PASSWORD: bWktY29udHJhc2XDsWEtZGVsLWN1cnNv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlvolumencurso
  namespace: aplicacioncurso
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldeploymentcurso
  namespace: aplicacioncurso
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysqldeploymentcurso
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: mysqlsecretcurso
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecretcurso
                  key: ROOT_PASSWORD
      volumes:
        - name: mysqlvolumencurso
          persistentVolumeClaim:
            claimName: mysqlvolumencurso

---
apiVersion: v1
kind: Service
metadata:
  name: mysqlservicecurso
  namespace: aplicacioncurso
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306